# -*- mode: ruby -*-
# vi: set ft=ruby :

cpus = 1
memory = 512 # RAM in MB. This should be enough for testing. The puppet master requires a lot more.
hostname_suffix = "local"

vms = {
  "haproxy" => {
    ip: "192.168.100.2",
    hostname: "haproxy.#{hostname_suffix}",
    ports: [],
    shares: [],
    cpus: cpus,
    memory: 1024,
    box: "centos/7",
    aliases: []
  },
  "ws1" => {
    ip: "192.168.101.2",
    hostname: "ws1.#{hostname_suffix}",
    ports: [],
    shares: [],
    cpus: cpus,
    memory: memory,
    box: "centos/7",
    aliases: []
  },
  "ws2" => {
    ip: "192.168.101.3",
    hostname: "ws2.#{hostname_suffix}",
    ports: [],
    shares: [],
    cpus: cpus,
    memory: memory,
    box: "centos/7",
    aliases: []
  },
  "db1" => {
    ip: "192.168.102.2",
    hostname: "db1.#{hostname_suffix}",
    ports: [],
    shares: [],
    cpus: cpus,
    memory: memory,
    box: "centos/7",
    aliases: []
  },
  "db2" => {
    ip: "192.168.102.3",
    hostname: "db2.#{hostname_suffix}",
    ports: [],
    shares: [],
    cpus: cpus,
    memory: memory,
    box: "centos/7",
    aliases: []
  },
}

inventory_groups = {
  loadbalancers: [
    "haproxy",
  ],
  webservers: [
    "ws1",
    "ws2",
  ],
  databaseservers: [
    "db1",
    "db2"
  ]
}

Vagrant.configure("2") do |config|

  config.landrush.enabled = true
  config.landrush.tld = hostname_suffix
  config.landrush.guest_redirect_dns = false

  vms.each_pair do |vm_name, vm_config|

    config.vm.define vm_name do |config|
      config.vm.box = vm_config[:box]
      config.vm.hostname = vm_config[:hostname]
      config.vm.network :private_network, ip: vm_config[:ip]

      vm_config[:aliases].each { |vm_alias|
        config.landrush.host vm_alias, vm_config[:ip]
      }


      vm_config[:shares].each { |share|
          config.vm.synced_folder share[:local], share[:remote]
      } # vm_config[:shares].each

      vm_config[:ports].each { |port_forwarding|
          config.vm.network :forwarded_port,
            host:  port_forwarding[:host_port],
            guest: port_forwarding[:guest_port],
            id:    port_forwarding[:id]
      } # vm_config[:ports].each

      config.vm.provider "virtualbox" do |vb|
        vb.name = vm_name
        vb.memory = vm_config[:memory]
        vb.cpus = vm_config[:cpus]
      end # :virtualbox

      config.vm.provision "ansible" do |ansible|
        ansible.groups = inventory_groups
        ansible.playbook = "playbook.yml"
        ansible.become = true

      end # :ansible

    end # config.vm.define
  end # vms.each_pair

end # Vagrant.config
