---
- name: Puppetmasters play book
  hosts: puppetmasters
  roles:
    - dump-vars
    - "the-paulus.puppet"

- name: Puppets play book
  hosts: puppets
  roles:
    - dump-vars
    - the-paulus.puppet-agent
