# -*- mode: ruby -*-
# vi: set ft=ruby :

cpus = 1
memory = 256 # RAM in MB. This should be enough for testing. The puppet master requires a lot more.
pm_memory = 4192
hostname_suffix = "example.com"

vms = {
  "puppetmaster" => {
    ip: "192.168.100.2",
    hostname: "puppetmaster",
    ports: [],
    shares: [
      { local: Dir.pwd + "/puppet-modules", remote: "/etc/puppetlabs/code/modules" }
    ],
    cpus: cpus,
    memory: pm_memory,
    #box: "ubuntu/precise64",
    box: "centos/7",
    aliases: [
      "puppet"
    ]
  },
  "creation" => {
    ip: "192.168.100.3",
    hostname: "creation",
    ports: [],
    shares: [],
    cpus: cpus,
    memory: pm_memory,
    box: "centos/7",
    aliases: []
  },
  "revenge" => {
    ip: "192.168.100.4",
    hostname: "revenge",
    ports: [],
    shares: [],
    cpus: cpus,
    memory: pm_memory,
    box: "centos/7",
    aliases: []
  },
  "blade" => {
    ip: '192.168.101.2',
    hostname: "blade",
    ports: [],
    shares: [],
    cpus: cpus,
    memory: memory,
    box: 'centos/7',
    aliases: []
  },
  "decapitron" => {
    ip: '192.168.101.3',
    hostname: "decapitron",
    ports: [],
    shares: [],
    cpus: cpus,
    memory: memory,
    box: 'ubuntu/precise64',
    aliases: []
  },
  "pinhead" => {
    ip: '192.168.101.4',
    hostname: "pinhead",
    ports: [],
    shares: [],
    cpus: cpus,
    memory: memory,
    box: 'debian/jessie64',
    aliases: []
  },
  "jester" => {
    ip: '192.168.101.5',
    hostname: "jester",
    ports: [],
    shares: [],
    cpus: cpus,
    memory: memory,
    box: 'debian/wheezy64',
    aliases: []
  },
}

inventory_groups = {
  puppetmasters: [
    "puppetmaster",
    "creation",
    "revenge",
  ],
  puppets: [
    "blade",
    "decapitron",
    "pinhead",
    "jester"
  ]
}

Vagrant.configure("2") do |config|

  vms.each_pair do |vm_name, vm_config|

    config.landrush.enabled = true
    config.landrush.tld = hostname_suffix
    config.landrush.guest_redirect_dns = false

    config.vm.define vm_name do |config|
      config.vm.box = vm_config[:box]
      config.vm.hostname = vm_config[:hostname] + '.' + hostname_suffix
      config.vm.network :private_network, ip: vm_config[:ip]

      vm_config[:aliases].each { |vm_alias|
        config.landrush.host vm_alias, vm_config[:ip]
      }

      vm_config[:shares].each { |share|
          config.vm.synced_folder share[:local], share[:remote]
      } # vm_config[:shares].each

      vm_config[:ports].each { |port_forwarding|
          config.vm.network :forwarded_port,
            host:  port_forwarding[:host_port],
            guest: port_forwarding[:guest_port],
            id:    port_forwarding[:id]
      } # vm_config[:ports].each

      config.vm.provider "virtualbox" do |vb|
        vb.name = vm_name
        vb.memory = vm_config[:memory]
        vb.cpus = vm_config[:cpus]
      end # :virtualbox

      config.vm.provision "ansible" do |ansible|
        ansible.groups = inventory_groups
        ansible.playbook = "playbook.yml"
        ansible.become = true

        #ansible.become_user = "root"
        #ansible.become_ask_pass = true
        #ansible.limit = "" # connect to ALL the vagrants!
        #ansible.ask_vault_pass = false # Change to true when using vaults.
        #ansible.host_key_checking = false
        #ansible.extra_vars = "" # string or hash
        #ansible.skip_tags = []
        #ansible.start_at_task = "Update web server intermediate certificate"
        #ansible.tags = []

      end # :ansible

    end # config.vm.define
  end # vms.each_pair

end # Vagrant.config
